### ISSUE TITLE
Service: allow to download and copy result

### ISSUE THREAD

**Issue by koriym** [filip26/eiger#106]
When the value converted by https://eiger.apicatalog.com/ is a large value that requires scrolling,
 it is very difficult to copy.

I've tried it in Chrome and Safari on my Mac, and it's equally difficult; Please heck in Chrome.
It would be nice if it could be downloaded.

**Comment by filip26** [comment]
Hi,
yes, the functionality is missing now.  Feel free to open PR.

**Comment by koriym** [comment]
> It would be nice if it could be downloaded.

This is something optional. I should open with the other PR.

> it is very difficult to copy.

Which browser did you test with? Seems nearly impossible to copy the result.

**Comment by filip26** [comment]
A new button allowing to copy a result has been added. Fixed in `alps-unified`  branch and online.
